language: node_js
node_js:
  - "8"

services:
  - docker

jobs:
  include:
    - stage: test
      node_js: "8"
      script:
        - npm run lint
        - npm test
        - cd e2e && ./run-tests.sh
